theme: jekyll-theme-cayman
name: "CBB 750 final project"
title: "Classifying cardiomyopathy v. heart failure for radiology patients with and without vectorized text data"
description: "A Ram, Jason Liu, Saejeong Park, Sarah Dudgeon"
