theme: jekyll-theme-cayman
name: "CBB 750 final project"
title: "CBB 750 final project -- group 1"
description: "Classifying cardiomyopathy v. heart failure for radiology patients with and without vectorized text data"
