---
title: "Look@data"
author: "Sarah Dudgeon"
date: "3/31/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(formattable)
library(VennDiagram)
library(RColorBrewer)
library(UpSetR)
```



```{r}
dat <- read.csv("mimic-iii-clinical-database-1.4/NOTEEVENTS.csv")
```


```{r}
# review the data frame

# columns in df
colnames(dat)
# number unique subjects
length(unique(dat$SUBJECT_ID))
# number subject rows
length(dat$SUBJECT_ID)
# frequency table for note types
table(dat$CATEGORY)
```


```{r}
# Make a csv file with on column: unique patient IDs

df_ptID <- as.data.frame(unique(dat$SUBJECT_ID))
colnames(df_ptID) <- "SUBJECT_ID"
write.csv(df_ptID,"SubjectsWithNotes.csv", row.names = FALSE) #file saves within the project folder (i.e. wd)
```



FREQUENCY TABLE:

```{r}
# make df of two columns: note category and frequency
df <- as.data.frame(table(dat$CATEGORY))
# rename columns
colnames(df) <- c("Category", "Frequency")
# format pretty and print in HTML knit
formattable(df, 
            align = c("l", "r"), 
            list(`Frequency` = color_bar("#71CA97")))

```

VENN DIAGRAMS:

```{r}
# make df of two columns: subject_id and category
df <- dat[,c("SUBJECT_ID","CATEGORY")]

# make vd of "Radiology", "Discharge Summary", and "ECG" 
venn.diagram(
        x = list(df[df$CATEGORY=="Radiology", 1],
                 df[df$CATEGORY=="Discharge summary", 1],
                 df[df$CATEGORY=="ECG", 1]
                 ),
        category.names = c("Radiology" , 
                           "Discharge Summary",
                           "ECG" 
                           ),
        filename = 'Rad-DS-ECG_venn_diagramm.png', #file save name - to wd
        output=TRUE,
        
        # Output features
        imagetype="png" ,
        height = 480 , 
        width = 480 , 
        resolution = 300,
        compression = "lzw",
        
        # Circles
        lwd = 2,
        lty = 'blank',
        fill = brewer.pal(3, "Pastel2"),
        
        # Numbers
        cex = .6,
        fontface = "bold",
        fontfamily = "sans",
        
        # Set names
        cat.cex = 0.6,
        cat.fontface = "bold",
        cat.default.pos = "outer",
        cat.pos = c(-27, 8, 135),
        cat.dist = c(0.055, 0.055, 0.085),
        cat.fontfamily = "sans",
        rotation = 1
)
```


UPSET PLOT:

```{r}
# upset plot is like a ven diagram but with many inputs
listInput <- list(
                 Radiology = as.vector(df[df$CATEGORY=="Radiology", 1]),
                 Nursing = as.vector(df[df$CATEGORY=="Nursing", 1]),
                 Physician = as.vector(df[df$CATEGORY=="Physician", 1]),
                 Case_Management = as.vector(df[df$CATEGORY=="Case Management", 1]),
                 Consult = as.vector(df[df$CATEGORY=="Consult", 1]),
                 Discharge_Summary = as.vector(df[df$CATEGORY=="Discharge summary", 1]),
                 ECG = as.vector(df[df$CATEGORY=="ECG", 1]),
                 Echo = as.vector(df[df$CATEGORY=="Echo", 1]),
                 General = as.vector(df[df$CATEGORY=="General", 1]),
                 Nursing_other = as.vector(df[df$CATEGORY=="Nursing/other", 1]),
                 Nutrition = as.vector(df[df$CATEGORY=="Nutrition", 1]),
                 Pharmacy = as.vector(df[df$CATEGORY=="Pharmacy", 1]),
                 Physician = as.vector(df[df$CATEGORY=="Physician", 1]),
                 Rehab_Services = as.vector(df[df$CATEGORY=="Rehab Services", 1]),
                 Respiratory = as.vector(df[df$CATEGORY=="Respiratory", 1]),
                 Social_Work = as.vector(df[df$CATEGORY=="Social Work", 1]))

upset(fromList(listInput),
      nintersects = 40, # selecting the top 40 intersects
      nsets = 16, # number sets, listed above - length of listInput
      
      # chart order/set-up
      order.by = "freq", 
      decreasing = T, 
      
      #font size/chart beautification
      mb.ratio = c(0.6, 0.4), 
      number.angles = 0, 
      text.scale = 0.9, 
      point.size = 2.8, 
      line.size = 1
      )
```






